In [1]:
(5,7)

(5, 7)

In [2]:
5, 7

(5, 7)

In [3]:
(5,)

(5,)

In [4]:
list_a = [1, 3, 5, 7, 9]
list_b = [3, 5, 6, 7, 9]
list_a + list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [5]:
import numpy as np
array_a = np.array([1, 3, 5, 7, 9])
array_b = np.array([3, 5, 6, 7, 9])
type(array_a)
array_a + array_b

array([ 4,  8, 11, 14, 18])

In [6]:
import numpy as np

l = [[1,2,3],[2,3,4]]
array = np.array(l)
array.ndim, array.shape, array.size, array.dtype


(2, (2, 3), 6, dtype('int64'))

In [7]:
import numpy as np
np.random.randn(10,5)

array([[ 0.64058951, -1.05131492,  1.00955784,  0.37574154,  1.34448613],
       [-0.27400185, -0.40242964, -0.75739131, -0.13534744, -0.81240165],
       [-0.89444231, -0.48650897, -0.83607319,  0.51922657,  1.17988855],
       [-2.04052592, -0.31088027,  0.64126751, -0.97161448, -0.98370535],
       [-1.05705445, -0.55105634, -0.39904268, -1.36505569,  0.79845721],
       [ 1.6304315 , -0.99675064,  0.4010763 ,  1.05301444,  1.31974061],
       [ 0.05169631, -0.11446532, -0.84860457,  0.41205616, -0.52210646],
       [ 0.36272433, -0.00743308, -0.59357846, -2.1259197 , -0.89472366],
       [ 0.84776043, -1.16493642, -1.0277526 , -0.21630087, -1.77557416],
       [ 0.47200635,  0.77721047,  0.13915572, -0.62238729,  1.00854198]])

In [8]:
#50個學生,每個學生有5個分數(50-100)
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 83,  83,  89,  99,  96],
       [ 82,  53,  96, 100,  87],
       [ 74,  50,  72,  74,  60],
       [ 96,  78,  80,  66,  83],
       [ 81,  75,  66,  77,  85],
       [ 60,  50,  57,  77,  63],
       [ 65,  90,  88,  92,  89],
       [ 65,  56,  69, 100,  54],
       [ 75,  88,  96,  51,  78],
       [ 92,  61,  78,  52,  76],
       [ 61,  84,  76,  59,  96],
       [ 56,  79,  58,  96,  89],
       [ 99,  77,  67,  70,  50],
       [ 97,  85,  56,  59,  69],
       [ 58,  77,  80,  93,  57],
       [ 67,  99,  99,  90,  83],
       [ 61,  76,  80,  54,  78],
       [ 54,  84,  86,  84,  95],
       [ 79,  80,  77,  61,  57],
       [ 93,  83,  54,  99,  94],
       [100,  72,  80,  78,  64],
       [ 62,  79,  74,  95,  63],
       [ 67,  63,  73,  70,  81],
       [ 50,  79,  68,  70,  96],
       [ 91,  91,  65,  51,  68],
       [ 89,  63,  73,  83,  96],
       [ 88,  72,  94,  68,  66],
       [ 50,  74,  61,  62,  83],
       [ 59,  97,  50,  77,  71],
       [ 76,  

In [9]:
#第一個學生
scores[0,:]
#前5個學生
scores[:5,:]
#最後5個學生
scores[-5:,:]

array([[ 95,  75,  95,  75,  60],
       [ 93,  57,  70,  59,  57],
       [100,  53,  80,  74,  93],
       [ 77,  90,  73,  69,  51],
       [ 78,  62,  80,  68,  70]])

In [10]:
#全班第1科的分數
scores[:,0]

array([ 83,  82,  74,  96,  81,  60,  65,  65,  75,  92,  61,  56,  99,
        97,  58,  67,  61,  54,  79,  93, 100,  62,  67,  50,  91,  89,
        88,  50,  59,  76,  97,  68,  59,  88,  99,  85,  65,  75,  61,
        64,  99,  53,  84,  69,  83,  95,  93, 100,  77,  78])

In [11]:
#全班第2科的分數
scores[:,1]

array([ 83,  53,  50,  78,  75,  50,  90,  56,  88,  61,  84,  79,  77,
        85,  77,  99,  76,  84,  80,  83,  72,  79,  63,  79,  91,  63,
        72,  74,  97,  79,  50,  61,  82,  66,  52,  60, 100,  98,  89,
        61,  78,  94,  75,  53,  72,  75,  57,  53,  90,  62])

In [12]:
#每位學生的總分
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4] 
total


array([450, 418, 330, 403, 384, 307, 424, 344, 388, 359, 376, 378, 363,
       366, 365, 438, 349, 403, 354, 423, 394, 373, 354, 363, 366, 404,
       388, 330, 354, 353, 384, 332, 397, 353, 390, 393, 384, 365, 351,
       347, 406, 341, 362, 360, 394, 400, 336, 400, 360, 358])

In [13]:
#使用統計的方法
#每個學生總分
np.sum(scores,axis=1)

array([450, 418, 330, 403, 384, 307, 424, 344, 388, 359, 376, 378, 363,
       366, 365, 438, 349, 403, 354, 423, 394, 373, 354, 363, 366, 404,
       388, 330, 354, 353, 384, 332, 397, 353, 390, 393, 384, 365, 351,
       347, 406, 341, 362, 360, 394, 400, 336, 400, 360, 358])

In [14]:
#每個學生平均
np.mean(scores,axis=1)

array([90. , 83.6, 66. , 80.6, 76.8, 61.4, 84.8, 68.8, 77.6, 71.8, 75.2,
       75.6, 72.6, 73.2, 73. , 87.6, 69.8, 80.6, 70.8, 84.6, 78.8, 74.6,
       70.8, 72.6, 73.2, 80.8, 77.6, 66. , 70.8, 70.6, 76.8, 66.4, 79.4,
       70.6, 78. , 78.6, 76.8, 73. , 70.2, 69.4, 81.2, 68.2, 72.4, 72. ,
       78.8, 80. , 67.2, 80. , 72. , 71.6])